### ISSUE TITLE
VectorDrawable Resource not found on pre-lollipop devices

### ISSUE THREAD

**Issue by slidenerd** [telly/MrVector#11]
I was trying to make a video on how to use your library and I used this vector_android.xml which is placed in the generic drawable folder
![snap 2015-02-04 at 11 09 20](https://cloud.githubusercontent.com/assets/5139030/6035732/5eaf151e-ac5e-11e4-9ffb-d8e4f44d5018.png)

The app crashes on pre-lollipop devices with this stacktrace

02-04 11:01:20.610    2683-2683/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{materialtest.vivz.slidenerd.materialtest/materialtest.vivz.slidenerd.materialtest.VectorTestActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class <unknown>
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at materialtest.vivz.slidenerd.materialtest.VectorTestActivity.onCreate(VectorTestActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at materialtest.vivz.slidenerd.materialtest.VectorTestActivity.onCreate(VectorTestActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/vector_android.xml from drawable resource ID #0x7f020042
            at android.content.res.Resources.loadDrawable(Resources.java:2091)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
            at android.widget.ImageView.<init>(ImageView.java:127)
            at android.widget.ImageView.<init>(ImageView.java:117)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at materialtest.vivz.slidenerd.materialtest.VectorTestActivity.onCreate(VectorTestActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:897)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:837)
            at android.content.res.Resources.loadDrawable(Resources.java:2087)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
            at android.widget.ImageView.<init>(ImageView.java:127)
            at android.widget.ImageView.<init>(ImageView.java:117)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at materialtest.vivz.slidenerd.materialtest.VectorTestActivity.onCreate(VectorTestActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

I used the custom Application class to register this drawable
package materialtest.vivz.slidenerd.materialtest;

import android.app.Application;
import android.content.Context;

import com.telly.mrvector.MrVector;

/**
 * Created by Windows on 30-01-2015.
 */
public class MyApplication extends Application {

    private static MyApplication sInstance;
    static {
        MrVector.register(R.drawable.vector_android);
    }
    public static MyApplication getInstance(){
        return sInstance;
    }

   ...

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(MrVector.wrap(base));
    }

    @Override
    public void onCreate() {
        super.onCreate();
        sInstance=this;
    }

}

I even tried switching my drawable and using your vector_android instead. It runs on Lollipop but crashes on 4.3 and kitkat. It works perfectly on all devices however if I inflate the drawable in code
Can you please tell me what I am doing wrong. I am using Android Studio to build this up. Thanks

**Comment by ozodrukh** [comment]
May you forgot to reference your custom Application class in AndroidManifest.xml

**Comment by slidenerd** [comment]
Not at all, this is my Manifest as well where I am using the MyApplication, i shifted the code to my Activity for registering MrVector , the app still crashes..with the same exception
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="materialtest.vivz.slidenerd.materialtest" >

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/title_activity_main" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".SubActivity"
            android:label="@string/title_activity_sub" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="materialtest.vivz.slidenerd.materialtest.MainActivity" />
        </activity>
        <activity
            android:name=".ActivityWithSlidingTabLayout"
            android:label="@string/title_activity_activity_using_tab_library" >
        </activity>
        <activity
            android:name=".VectorTestActivity"
            android:label="@string/title_activity_vector_test" >
        </activity>
    </application>

</manifest>

**Comment by eveliotc** [comment]
@slidenerd nice avatar, inflate from layout (the way you are using) is work in progress, only manual `inflate` is supported at this point, also make sure that your xml drawable is on `drawable` or similar not only in `drawable-21`

**Comment by slidenerd** [comment]
No probs, I understand Thanks for all your help,  I have made a tutorial video of your library by the way, if its good add this to your doc so that it can help someone https://www.youtube.com/watch?v=uenoqUpxgI8 thanks again

**Comment by eveliotc** [comment]
@slidenerd that's pretty cool, I'll add to the README later today, note that for `inflate` you don't need to register drawable ids for that, and you can also use @ozodrukh converter to relief the pain of duplicated attributes

**Comment by slidenerd** [comment]
thanks you can close this issue, I tried to use AnimatedVectorDrawable but I guess that doesnt work currently, do update your README file once your library is fully functional, thanks

**Comment by sureshbora1989** [comment]
I also faced the same issue. As it do not inflate from layout. However if i download google play demo it work on kitkat.
